{% set name = "wstool" %}
{% set version = "0.1.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vcstools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f04621acda755a45896db2d3a84131f96cf69905515997637b4568f3fad5c46e
  patches:
    - console_scripts.patch  # [win]

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wstool = wstool.wstool_cli:main  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - vcstools >=0.1.38
    - python-dateutil

test:
  imports:
    - wstool
  commands:
    - pip check
    - wstool --help  # [not win or py>=30]
  requires:
    - pip

about:
  home: http://wiki.ros.org/wstool
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: workspace multi-SCM commands

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
